 # This is a basic workflow to help you get started with Actions

name: CI SPASE Validation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup
      run: |
        sudo apt install nodejs 
        sudo npm install spase-resource-tools -g --unsafe-perm

    # Runs a set of commands using the runners shell
    - name: Run script
      run: |
        echo "GitHub Fork Base = $GITHUB_HEAD_REF"
        echo "GitHub Commit SHA = $GITHUB_SHA"
        git diff "$GITHUB_HEAD_REF..$GITHUB_SHA"
        for f in `git diff --name-only "$GITHUB_HEAD_REF..$GITHUB_SHA"`; do spase-validate $f; done 
        
